kind = "app"
categories = ["Office"]
icon = "assets/app-icon/hicolor/256x256/apps/ai.storyteller.wordcraft.png"

[linux.x86_64]
asset = "wordcraft-{version}-linux-x86_64.tar.gz"
exec = "wordcraft-{version}-linux-x86_64/usr/bin/wordcraft"

[linux.aarch64]
asset = "wordcraft-{version}-linux-aarch64.tar.gz"
exec = "wordcraft-{version}-linux-aarch64/usr/bin/wordcraft"
