//! Named math characters: Math AutoCorrect while typing in an equation (`\alpha` + space → α)
//! and LaTeX conversion. Names are the usual TeX names plus the linear-format operators
//! (`\sqrt` → √, `\above` → ┴, `\matrix` → ■…).

/// (name without the backslash, character). When a character has several names the first one
/// listed is the one LaTeX output uses.
pub const SYMBOLS: &[(&str, char)] = &[
    // Greek.
    ("alpha", 'α'),
    ("beta", 'β'),
    ("gamma", 'γ'),
    ("delta", 'δ'),
    ("epsilon", 'ϵ'),
    ("varepsilon", 'ε'),
    ("zeta", 'ζ'),
    ("eta", 'η'),
    ("theta", 'θ'),
    ("vartheta", 'ϑ'),
    ("iota", 'ι'),
    ("kappa", 'κ'),
    ("varkappa", 'ϰ'),
    ("lambda", 'λ'),
    ("mu", 'μ'),
    ("nu", 'ν'),
    ("xi", 'ξ'),
    ("omicron", 'ο'),
    ("pi", 'π'),
    ("varpi", 'ϖ'),
    ("rho", 'ρ'),
    ("varrho", 'ϱ'),
    ("sigma", 'σ'),
    ("varsigma", 'ς'),
    ("tau", 'τ'),
    ("upsilon", 'υ'),
    ("phi", 'ϕ'),
    ("varphi", 'φ'),
    ("chi", 'χ'),
    ("psi", 'ψ'),
    ("omega", 'ω'),
    ("Alpha", 'Α'),
    ("Beta", 'Β'),
    ("Gamma", 'Γ'),
    ("Delta", 'Δ'),
    ("Epsilon", 'Ε'),
    ("Zeta", 'Ζ'),
    ("Eta", 'Η'),
    ("Theta", 'Θ'),
    ("Iota", 'Ι'),
    ("Kappa", 'Κ'),
    ("Lambda", 'Λ'),
    ("Mu", 'Μ'),
    ("Nu", 'Ν'),
    ("Xi", 'Ξ'),
    ("Omicron", 'Ο'),
    ("Pi", 'Π'),
    ("Rho", 'Ρ'),
    ("Sigma", 'Σ'),
    ("Tau", 'Τ'),
    ("Upsilon", 'Υ'),
    ("Phi", 'Φ'),
    ("Chi", 'Χ'),
    ("Psi", 'Ψ'),
    ("Omega", 'Ω'),
    ("digamma", 'ϝ'),
    // Binary operators.
    ("pm", '±'),
    ("mp", '∓'),
    ("times", '×'),
    ("div", '÷'),
    ("cdot", '⋅'),
    ("bullet", '∙'),
    ("ast", '∗'),
    ("star", '⋆'),
    ("circ", '∘'),
    ("oplus", '⊕'),
    ("ominus", '⊖'),
    ("otimes", '⊗'),
    ("oslash", '⊘'),
    ("odot", '⊙'),
    ("cup", '∪'),
    ("cap", '∩'),
    ("uplus", '⊎'),
    ("sqcup", '⊔'),
    ("sqcap", '⊓'),
    ("vee", '∨'),
    ("wedge", '∧'),
    ("setminus", '∖'),
    ("wr", '≀'),
    ("diamond", '⋄'),
    ("dagger", '†'),
    ("ddagger", '‡'),
    ("amalg", '⨿'),
    ("dotplus", '∔'),
    ("ltimes", '⋉'),
    ("rtimes", '⋊'),
    // Relations.
    ("le", '≤'),
    ("leq", '≤'),
    ("ge", '≥'),
    ("geq", '≥'),
    ("ne", '≠'),
    ("neq", '≠'),
    ("approx", '≈'),
    ("equiv", '≡'),
    ("sim", '∼'),
    ("simeq", '≃'),
    ("cong", '≅'),
    ("propto", '∝'),
    ("ll", '≪'),
    ("gg", '≫'),
    ("prec", '≺'),
    ("succ", '≻'),
    ("preceq", '≼'),
    ("succeq", '≽'),
    ("subset", '⊂'),
    ("supset", '⊃'),
    ("subseteq", '⊆'),
    ("supseteq", '⊇'),
    ("sqsubseteq", '⊑'),
    ("sqsupseteq", '⊒'),
    ("in", '∈'),
    ("ni", '∋'),
    ("notin", '∉'),
    ("perp", '⊥'),
    ("parallel", '∥'),
    ("mid", '∣'),
    ("nmid", '∤'),
    ("asymp", '≍'),
    ("doteq", '≐'),
    ("models", '⊨'),
    ("vdash", '⊢'),
    ("dashv", '⊣'),
    ("bowtie", '⋈'),
    ("coloneq", '≔'),
    ("defeq", '≝'),
    ("triangleq", '≜'),
    ("nless", '≮'),
    ("ngtr", '≯'),
    ("nleq", '≰'),
    ("ngeq", '≱'),
    ("nsim", '≁'),
    ("ncong", '≇'),
    ("nequiv", '≢'),
    ("nsubset", '⊄'),
    ("nsupset", '⊅'),
    ("nsubseteq", '⊈'),
    ("nsupseteq", '⊉'),
    ("subsetneq", '⊊'),
    ("supsetneq", '⊋'),
    ("lesssim", '≲'),
    ("gtrsim", '≳'),
    ("therefore", '∴'),
    ("because", '∵'),
    // Arrows.
    ("rightarrow", '→'),
    ("to", '→'),
    ("leftarrow", '←'),
    ("gets", '←'),
    ("leftrightarrow", '↔'),
    ("uparrow", '↑'),
    ("downarrow", '↓'),
    ("updownarrow", '↕'),
    ("Rightarrow", '⇒'),
    ("Leftarrow", '⇐'),
    ("Leftrightarrow", '⇔'),
    ("Uparrow", '⇑'),
    ("Downarrow", '⇓'),
    ("Updownarrow", '⇕'),
    ("longrightarrow", '⟶'),
    ("longleftarrow", '⟵'),
    ("longleftrightarrow", '⟷'),
    ("Longrightarrow", '⟹'),
    ("Longleftarrow", '⟸'),
    ("Longleftrightarrow", '⟺'),
    ("implies", '⟹'),
    ("iff", '⟺'),
    ("mapsto", '↦'),
    ("longmapsto", '⟼'),
    ("nearrow", '↗'),
    ("searrow", '↘'),
    ("swarrow", '↙'),
    ("nwarrow", '↖'),
    ("hookleftarrow", '↩'),
    ("hookrightarrow", '↪'),
    ("leftharpoonup", '↼'),
    ("leftharpoondown", '↽'),
    ("rightharpoonup", '⇀'),
    ("rightharpoondown", '⇁'),
    ("rightleftharpoons", '⇌'),
    ("leftrightharpoons", '⇋'),
    ("circlearrowleft", '↺'),
    ("circlearrowright", '↻'),
    // Big operators.
    ("sum", '∑'),
    ("prod", '∏'),
    ("coprod", '∐'),
    ("int", '∫'),
    ("iint", '∬'),
    ("iiint", '∭'),
    ("oint", '∮'),
    ("oiint", '∯'),
    ("oiiint", '∰'),
    ("bigcup", '⋃'),
    ("bigcap", '⋂'),
    ("bigvee", '⋁'),
    ("bigwedge", '⋀'),
    ("bigoplus", '⨁'),
    ("bigotimes", '⨂'),
    ("bigodot", '⨀'),
    ("biguplus", '⨄'),
    ("bigsqcup", '⨆'),
    // Brackets.
    ("langle", '⟨'),
    ("rangle", '⟩'),
    ("lceil", '⌈'),
    ("rceil", '⌉'),
    ("lfloor", '⌊'),
    ("rfloor", '⌋'),
    ("lbrack", '['),
    ("rbrack", ']'),
    ("lbrace", '{'),
    ("rbrace", '}'),
    ("Vert", '‖'),
    ("norm", '‖'),
    ("vert", '|'),
    ("lbbrack", '⟦'),
    ("rbbrack", '⟧'),
    // Miscellaneous.
    ("infty", '∞'),
    ("partial", '∂'),
    ("nabla", '∇'),
    ("forall", '∀'),
    ("exists", '∃'),
    ("nexists", '∄'),
    ("neg", '¬'),
    ("lnot", '¬'),
    ("emptyset", '∅'),
    ("varnothing", '∅'),
    ("hbar", 'ℏ'),
    ("ell", 'ℓ'),
    ("Re", 'ℜ'),
    ("Im", 'ℑ'),
    ("wp", '℘'),
    ("aleph", 'ℵ'),
    ("beth", 'ℶ'),
    ("gimel", 'ℷ'),
    ("daleth", 'ℸ'),
    ("degree", '°'),
    ("angle", '∠'),
    ("measuredangle", '∡'),
    ("sphericalangle", '∢'),
    ("rightangle", '∟'),
    ("triangle", '△'),
    ("square", '□'),
    ("blacksquare", '■'),
    ("qed", '∎'),
    ("top", '⊤'),
    ("bot", '⊥'),
    ("cdots", '⋯'),
    ("ldots", '…'),
    ("dots", '…'),
    ("vdots", '⋮'),
    ("ddots", '⋱'),
    ("adots", '⋰'),
    ("prime", '′'),
    ("dprime", '″'),
    ("trprime", '‴'),
    ("dd", 'ⅆ'),
    ("Dd", 'ⅅ'),
    ("ee", 'ⅇ'),
    ("ii", 'ⅈ'),
    ("jj", 'ⅉ'),
    ("imath", 'ı'),
    ("jmath", 'ȷ'),
    ("complement", '∁'),
    ("Angstrom", 'Å'),
    ("mho", '℧'),
    ("eth", 'ð'),
    ("flat", '♭'),
    ("natural", '♮'),
    ("sharp", '♯'),
    ("clubsuit", '♣'),
    ("diamondsuit", '♢'),
    ("heartsuit", '♡'),
    ("spadesuit", '♠'),
    // Spaces.
    ("quad", '\u{2003}'),
    ("emsp", '\u{2003}'),
    ("ensp", '\u{2002}'),
    ("thicksp", '\u{2005}'),
    ("medsp", '\u{205F}'),
    ("thinsp", '\u{2009}'),
    ("hairsp", '\u{200A}'),
    ("nbsp", '\u{A0}'),
    ("zwsp", '\u{200B}'),
    // Linear-format operators (build-up).
    ("sqrt", '√'),
    ("cbrt", '∛'),
    ("qdrt", '∜'),
    ("matrix", '■'),
    ("eqarray", '█'),
    ("above", '┴'),
    ("below", '┬'),
    ("of", '▒'),
    ("naryand", '▒'),
    ("funcapply", '\u{2061}'),
    ("box", '□'),
    ("rect", '▭'),
    ("overbar", '¯'),
    ("underbar", '▁'),
    ("phantom", '⟡'),
    ("overbrace", '⏞'),
    ("underbrace", '⏟'),
    ("overparen", '⏜'),
    ("underparen", '⏝'),
    ("atop", '¦'),
    ("over", '/'),
    ("ldiv", '∕'),
    ("sdiv", '⁄'),
    ("begin", '〖'),
    ("end", '〗'),
    ("left", '├'),
    ("right", '┤'),
    ("eqno", '#'),
    ("placeholder", '⬚'),
    // Accents (combining, typed after the base).
    ("hat", '\u{302}'),
    ("check", '\u{30C}'),
    ("tilde", '\u{303}'),
    ("acute", '\u{301}'),
    ("grave", '\u{300}'),
    ("dot", '\u{307}'),
    ("ddot", '\u{308}'),
    ("dddot", '\u{20DB}'),
    ("breve", '\u{306}'),
    ("bar", '\u{305}'),
    ("Bar", '\u{33F}'),
    ("vec", '\u{20D7}'),
    ("tvec", '\u{20E1}'),
    ("lhvec", '\u{20D0}'),
    ("hvec", '\u{20D1}'),
];

/// The character for a name (`alpha` → α), including `doubleR`, `scriptL`, `frakturg`.
pub fn symbol(name: &str) -> Option<char> {
    if let Some((_, c)) = SYMBOLS.iter().find(|(n, _)| *n == name) {
        return Some(*c);
    }
    for (prefix, scr) in [("double", crate::math::MScr::DoubleStruck), ("script", crate::math::MScr::Script), ("fraktur", crate::math::MScr::Fraktur)]
    {
        if let Some(rest) = name.strip_prefix(prefix) {
            let mut cs = rest.chars();
            if let (Some(c), None) = (cs.next(), cs.next())
                && c.is_ascii_alphanumeric()
            {
                let m = crate::math::math_alnum(c, false, false, scr);
                if m != c {
                    return Some(m);
                }
            }
        }
    }
    None
}

/// The (first) name of a character.
pub fn name_of(c: char) -> Option<&'static str> {
    SYMBOLS.iter().find(|(_, s)| *s == c).map(|(n, _)| *n)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn names_resolve() {
        assert_eq!(symbol("alpha"), Some('α'));
        assert_eq!(symbol("doubleR"), Some('ℝ'));
        assert_eq!(symbol("scriptL"), Some('ℒ'));
        assert_eq!(symbol("nonesuch"), None);
        assert_eq!(name_of('≤'), Some("le"));
        // No name is listed twice.
        let mut names: Vec<&str> = SYMBOLS.iter().map(|(n, _)| *n).collect();
        names.sort_unstable();
        let before = names.len();
        names.dedup();
        assert_eq!(before, names.len());
    }
}
